//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';

//Password Reset
export const  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const EMAIL_VERIFICATION_REQUEST_SENT = 'EMAIL_VERIFICATION_REQUEST_SENT';
export const EMAIL_VERIFICATION_REQUEST_FAILED = 'EMAIL_VERIFICATION_REQUEST_FAILED';
export const EMAIL_VERIFICATION_CONFIRMED = 'EMAIL_VERIFICATION_CONFIRMED';
export const EMAIL_VERIFICATION_CONFIRM_FAILED = 'EMAIL_VERIFICATION_CONFIRM_FAILED';

export const LOAD_USERS = 'LOAD_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const USERS_ERROR = 'USERS_ERROR';

export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';



//General
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERROR = 'SET_ERROR';


// Chat Types
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const CLEAR_ACTIVE_CHAT = 'CLEAR_ACTIVE_CHAT';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const MARK_MESSAGES_READ = 'MARK_MESSAGES_READ';
export const SET_TYPING = 'SET_TYPING';
export const CLEAR_TYPING = 'CLEAR_TYPING';
export const UPDATE_ONLINE_USERS = 'UPDATE_ONLINE_USERS';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const CHAT_ERROR = 'CHAT_ERROR';
export const CLEAR_CHAT_ERRORS = 'CLEAR_CHAT_ERRORS';

// Student CRUD operations
export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

export const GET_STUDENT_BY_USER_REQUEST = 'GET_STUDENT_BY_USER_REQUEST';
export const GET_STUDENT_BY_USER_SUCCESS = 'GET_STUDENT_BY_USER_SUCCESS';
export const GET_STUDENT_BY_USER_FAIL = 'GET_STUDENT_BY_USER_FAIL';

// Performance and Progress operations
export const ADD_PERFORMANCE_SCORE_REQUEST = 'ADD_PERFORMANCE_SCORE_REQUEST';
export const ADD_PERFORMANCE_SCORE_SUCCESS = 'ADD_PERFORMANCE_SCORE_SUCCESS';
export const ADD_PERFORMANCE_SCORE_FAIL = 'ADD_PERFORMANCE_SCORE_FAIL';

export const UPDATE_COURSE_PROGRESS_REQUEST = 'UPDATE_COURSE_PROGRESS_REQUEST';
export const UPDATE_COURSE_PROGRESS_SUCCESS = 'UPDATE_COURSE_PROGRESS_SUCCESS';
export const UPDATE_COURSE_PROGRESS_FAIL = 'UPDATE_COURSE_PROGRESS_FAIL';

// Additional actions
export const CLEAR_STUDENT_ERRORS = 'CLEAR_STUDENT_ERRORS';
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
export const CLEAR_CURRENT_STUDENT = 'CLEAR_CURRENT_STUDENT';
export const RESET_STUDENT_STATE = 'RESET_STUDENT_STATE';