//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';

//Password Reset
export const  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const EMAIL_VERIFICATION_REQUEST_SENT = 'EMAIL_VERIFICATION_REQUEST_SENT';
export const EMAIL_VERIFICATION_REQUEST_FAILED = 'EMAIL_VERIFICATION_REQUEST_FAILED';
export const EMAIL_VERIFICATION_CONFIRMED = 'EMAIL_VERIFICATION_CONFIRMED';
export const EMAIL_VERIFICATION_CONFIRM_FAILED = 'EMAIL_VERIFICATION_CONFIRM_FAILED';

export const LOAD_USERS = 'LOAD_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const USERS_ERROR = 'USERS_ERROR';

export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';



//General
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERROR = 'SET_ERROR';


// Chat Types
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const CLEAR_ACTIVE_CHAT = 'CLEAR_ACTIVE_CHAT';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const MARK_MESSAGES_READ = 'MARK_MESSAGES_READ';
export const SET_TYPING = 'SET_TYPING';
export const CLEAR_TYPING = 'CLEAR_TYPING';
export const UPDATE_ONLINE_USERS = 'UPDATE_ONLINE_USERS';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const CHAT_ERROR = 'CHAT_ERROR';
export const CLEAR_CHAT_ERRORS = 'CLEAR_CHAT_ERRORS';

// Student CRUD operations
export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

export const GET_STUDENT_BY_USER_REQUEST = 'GET_STUDENT_BY_USER_REQUEST';
export const GET_STUDENT_BY_USER_SUCCESS = 'GET_STUDENT_BY_USER_SUCCESS';
export const GET_STUDENT_BY_USER_FAIL = 'GET_STUDENT_BY_USER_FAIL';

// Performance and Progress operations
export const ADD_PERFORMANCE_SCORE_REQUEST = 'ADD_PERFORMANCE_SCORE_REQUEST';
export const ADD_PERFORMANCE_SCORE_SUCCESS = 'ADD_PERFORMANCE_SCORE_SUCCESS';
export const ADD_PERFORMANCE_SCORE_FAIL = 'ADD_PERFORMANCE_SCORE_FAIL';

export const UPDATE_COURSE_PROGRESS_REQUEST = 'UPDATE_COURSE_PROGRESS_REQUEST';
export const UPDATE_COURSE_PROGRESS_SUCCESS = 'UPDATE_COURSE_PROGRESS_SUCCESS';
export const UPDATE_COURSE_PROGRESS_FAIL = 'UPDATE_COURSE_PROGRESS_FAIL';

// Additional actions
export const CLEAR_STUDENT_ERRORS = 'CLEAR_STUDENT_ERRORS';
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
export const CLEAR_CURRENT_STUDENT = 'CLEAR_CURRENT_STUDENT';
export const RESET_STUDENT_STATE = 'RESET_STUDENT_STATE';

// Course CRUD Operations
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';

export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL';

// Enrollment Operations
export const ENROLL_STUDENT_REQUEST = 'ENROLL_STUDENT_REQUEST';
export const ENROLL_STUDENT_SUCCESS = 'ENROLL_STUDENT_SUCCESS';
export const ENROLL_STUDENT_FAIL = 'ENROLL_STUDENT_FAIL';

export const UNENROLL_STUDENT_REQUEST = 'UNENROLL_STUDENT_REQUEST';
export const UNENROLL_STUDENT_SUCCESS = 'UNENROLL_STUDENT_SUCCESS';
export const UNENROLL_STUDENT_FAIL = 'UNENROLL_STUDENT_FAIL';

// Course Students
export const GET_COURSE_STUDENTS_REQUEST = 'GET_COURSE_STUDENTS_REQUEST';
export const GET_COURSE_STUDENTS_SUCCESS = 'GET_COURSE_STUDENTS_SUCCESS';
export const GET_COURSE_STUDENTS_FAIL = 'GET_COURSE_STUDENTS_FAIL';

// Course Modules
export const GET_COURSE_MODULES_REQUEST = 'GET_COURSE_MODULES_REQUEST';
export const GET_COURSE_MODULES_SUCCESS = 'GET_COURSE_MODULES_SUCCESS';
export const GET_COURSE_MODULES_FAIL = 'GET_COURSE_MODULES_FAIL';

export const UPDATE_COURSE_MODULE_REQUEST = 'UPDATE_COURSE_MODULE_REQUEST';
export const UPDATE_COURSE_MODULE_SUCCESS = 'UPDATE_COURSE_MODULE_SUCCESS';
export const UPDATE_COURSE_MODULE_FAIL = 'UPDATE_COURSE_MODULE_FAIL';

// Announcements
export const ADD_COURSE_ANNOUNCEMENT_REQUEST = 'ADD_COURSE_ANNOUNCEMENT_REQUEST';
export const ADD_COURSE_ANNOUNCEMENT_SUCCESS = 'ADD_COURSE_ANNOUNCEMENT_SUCCESS';
export const ADD_COURSE_ANNOUNCEMENT_FAIL = 'ADD_COURSE_ANNOUNCEMENT_FAIL';

// Advanced Search
export const ADVANCED_COURSE_SEARCH_REQUEST = 'ADVANCED_COURSE_SEARCH_REQUEST';
export const ADVANCED_COURSE_SEARCH_SUCCESS = 'ADVANCED_COURSE_SEARCH_SUCCESS';
export const ADVANCED_COURSE_SEARCH_FAIL = 'ADVANCED_COURSE_SEARCH_FAIL';

// Utility Actions
export const CLEAR_COURSE_ERRORS = 'CLEAR_COURSE_ERRORS';
export const CLEAR_COURSE_SUCCESS = 'CLEAR_COURSE_SUCCESS';
export const SET_COURSE_LOADING = 'SET_COURSE_LOADING';
export const RESET_COURSE_STATE = 'RESET_COURSE_STATE';


// Student Assignment Types
export const SUBMIT_ASSIGNMENT_REQUEST = 'SUBMIT_ASSIGNMENT_REQUEST';
export const SUBMIT_ASSIGNMENT_SUCCESS = 'SUBMIT_ASSIGNMENT_SUCCESS';
export const SUBMIT_ASSIGNMENT_FAIL = 'SUBMIT_ASSIGNMENT_FAIL';

export const GET_ASSIGNMENTS_REQUEST = 'GET_ASSIGNMENTS_REQUEST';
export const GET_ASSIGNMENTS_SUCCESS = 'GET_ASSIGNMENTS_SUCCESS';
export const GET_ASSIGNMENTS_FAIL = 'GET_ASSIGNMENTS_FAIL';

// Student Quiz Types
export const SUBMIT_QUIZ_REQUEST = 'SUBMIT_QUIZ_REQUEST';
export const SUBMIT_QUIZ_SUCCESS = 'SUBMIT_QUIZ_SUCCESS';
export const SUBMIT_QUIZ_FAIL = 'SUBMIT_QUIZ_FAIL';

// Module Completion Types
export const MARK_MODULE_COMPLETE_REQUEST = 'MARK_MODULE_COMPLETE_REQUEST';
export const MARK_MODULE_COMPLETE_SUCCESS = 'MARK_MODULE_COMPLETE_SUCCESS';
export const MARK_MODULE_COMPLETE_FAIL = 'MARK_MODULE_COMPLETE_FAIL';

// Progress Details Types
export const GET_PROGRESS_DETAILS_REQUEST = 'GET_PROGRESS_DETAILS_REQUEST';
export const GET_PROGRESS_DETAILS_SUCCESS = 'GET_PROGRESS_DETAILS_SUCCESS';
export const GET_PROGRESS_DETAILS_FAIL = 'GET_PROGRESS_DETAILS_FAIL';


// Add Note
export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAIL = "ADD_NOTE_FAIL";

// Update Note
export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL";

// Delete Note
export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL";

// Get All Notes
export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAIL = "GET_NOTES_FAIL";

// Get Single Note
export const GET_NOTE_REQUEST = "GET_NOTE_REQUEST";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const GET_NOTE_FAIL = "GET_NOTE_FAIL";
export const GET_STUDENT_STATS_REQUEST = "GET_STUDENT_STATS_REQUEST"
export const GET_STUDENT_STATS_SUCCESS = "GET_STUDENT_STATS_SUCCESS";
export const GET_STUDENT_STATS_FAIL = "GET_STUDENT_STATS_FAIL";
export const GET_WEEKLY_ACTIVITY_REQUEST = "GET_WEEKLY_ACTIVITY_REQUEST";
export const GET_WEEKLY_ACTIVITY_SUCCESS = "GET_WEEKLY_ACTIVITY_SUCCESS";
export const GET_WEEKLY_ACTIVITY_FAIL = "GET_WEEKLY_ACTIVITY_FAIL";

export const FORUM_TYPES = {
  // Dashboard
  GET_FORUM_DASHBOARD_REQUEST: 'GET_FORUM_DASHBOARD_REQUEST',
  GET_FORUM_DASHBOARD_SUCCESS: 'GET_FORUM_DASHBOARD_SUCCESS',
  GET_FORUM_DASHBOARD_FAILURE: 'GET_FORUM_DASHBOARD_FAILURE',

  // Categories
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  // Posts
  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

  GET_POST_REQUEST: 'GET_POST_REQUEST',
  GET_POST_SUCCESS: 'GET_POST_SUCCESS',
  GET_POST_FAILURE: 'GET_POST_FAILURE',

  CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',

  TOGGLE_POST_LIKE_REQUEST: 'TOGGLE_POST_LIKE_REQUEST',
  TOGGLE_POST_LIKE_SUCCESS: 'TOGGLE_POST_LIKE_SUCCESS',
  TOGGLE_POST_LIKE_FAILURE: 'TOGGLE_POST_LIKE_FAILURE',

  // Comments
  ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

  TOGGLE_COMMENT_LIKE_REQUEST: 'TOGGLE_COMMENT_LIKE_REQUEST',
  TOGGLE_COMMENT_LIKE_SUCCESS: 'TOGGLE_COMMENT_LIKE_SUCCESS',
  TOGGLE_COMMENT_LIKE_FAILURE: 'TOGGLE_COMMENT_LIKE_FAILURE',

  // Search
  SEARCH_POSTS_REQUEST: 'SEARCH_POSTS_REQUEST',
  SEARCH_POSTS_SUCCESS: 'SEARCH_POSTS_SUCCESS',
  SEARCH_POSTS_FAILURE: 'SEARCH_POSTS_FAILURE',

  // UI Actions
  SET_ACTIVE_CATEGORY: 'SET_ACTIVE_CATEGORY',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  CLEAR_CURRENT_POST: 'CLEAR_CURRENT_POST',
  CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
  SET_FORUM_LOADING: 'SET_FORUM_LOADING',
  CLEAR_FORUM_ERRORS: 'CLEAR_FORUM_ERRORS'
};

// types/adminForumTypes.js
export const ADMIN_FORUM_LOADING = 'ADMIN_FORUM_LOADING';
export const ADMIN_FORUM_ERROR = 'ADMIN_FORUM_ERROR';
export const ADMIN_FORUM_CLEAR_ERROR = 'ADMIN_FORUM_CLEAR_ERROR';

// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

// Posts
export const TOGGLE_PIN_POST_SUCCESS = 'TOGGLE_PIN_POST_SUCCESS';
export const TOGGLE_LOCK_POST_SUCCESS = 'TOGGLE_LOCK_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

// Analytics
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';




// Study Group Types
export const STUDY_GROUP_TYPES = {
  // Dashboard Data
  GET_MY_GROUPS_REQUEST: 'GET_MY_GROUPS_REQUEST',
  GET_MY_GROUPS_SUCCESS: 'GET_MY_GROUPS_SUCCESS',
  GET_MY_GROUPS_FAIL: 'GET_MY_GROUPS_FAIL',

  GET_RECOMMENDED_GROUPS_REQUEST: 'GET_RECOMMENDED_GROUPS_REQUEST',
  GET_RECOMMENDED_GROUPS_SUCCESS: 'GET_RECOMMENDED_GROUPS_SUCCESS',
  GET_RECOMMENDED_GROUPS_FAIL: 'GET_RECOMMENDED_GROUPS_FAIL',

  GET_UPCOMING_SESSIONS_REQUEST: 'GET_UPCOMING_SESSIONS_REQUEST',
  GET_UPCOMING_SESSIONS_SUCCESS: 'GET_UPCOMING_SESSIONS_SUCCESS',
  GET_UPCOMING_SESSIONS_FAIL: 'GET_UPCOMING_SESSIONS_FAIL',

  GET_GROUP_STATS_REQUEST: 'GET_GROUP_STATS_REQUEST',
  GET_GROUP_STATS_SUCCESS: 'GET_GROUP_STATS_SUCCESS',
  GET_GROUP_STATS_FAIL: 'GET_GROUP_STATS_FAIL',

  // Group Management
  CREATE_GROUP_REQUEST: 'CREATE_GROUP_REQUEST',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_FAIL: 'CREATE_GROUP_FAIL',

  GET_GROUP_DETAILS_REQUEST: 'GET_GROUP_DETAILS_REQUEST',
  GET_GROUP_DETAILS_SUCCESS: 'GET_GROUP_DETAILS_SUCCESS',
  GET_GROUP_DETAILS_FAIL: 'GET_GROUP_DETAILS_FAIL',

  JOIN_GROUP_REQUEST: 'JOIN_GROUP_REQUEST',
  JOIN_GROUP_SUCCESS: 'JOIN_GROUP_SUCCESS',
  JOIN_GROUP_FAIL: 'JOIN_GROUP_FAIL',

  LEAVE_GROUP_REQUEST: 'LEAVE_GROUP_REQUEST',
  LEAVE_GROUP_SUCCESS: 'LEAVE_GROUP_SUCCESS',
  LEAVE_GROUP_FAIL: 'LEAVE_GROUP_FAIL',

  // Study Sessions
  CREATE_SESSION_REQUEST: 'CREATE_SESSION_REQUEST',
  CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
  CREATE_SESSION_FAIL: 'CREATE_SESSION_FAIL',

  GET_GROUP_SESSIONS_REQUEST: 'GET_GROUP_SESSIONS_REQUEST',
  GET_GROUP_SESSIONS_SUCCESS: 'GET_GROUP_SESSIONS_SUCCESS',
  GET_GROUP_SESSIONS_FAIL: 'GET_GROUP_SESSIONS_FAIL',

  GET_MY_UPCOMING_SESSIONS_REQUEST: 'GET_MY_UPCOMING_SESSIONS_REQUEST',
  GET_MY_UPCOMING_SESSIONS_SUCCESS: 'GET_MY_UPCOMING_SESSIONS_SUCCESS',
  GET_MY_UPCOMING_SESSIONS_FAIL: 'GET_MY_UPCOMING_SESSIONS_FAIL',

  GET_SESSION_DETAILS_REQUEST: 'GET_SESSION_DETAILS_REQUEST',
  GET_SESSION_DETAILS_SUCCESS: 'GET_SESSION_DETAILS_SUCCESS',
  GET_SESSION_DETAILS_FAIL: 'GET_SESSION_DETAILS_FAIL',

  REGISTER_FOR_SESSION_REQUEST: 'REGISTER_FOR_SESSION_REQUEST',
  REGISTER_FOR_SESSION_SUCCESS: 'REGISTER_FOR_SESSION_SUCCESS',
  REGISTER_FOR_SESSION_FAIL: 'REGISTER_FOR_SESSION_FAIL',

  MARK_ATTENDANCE_REQUEST: 'MARK_ATTENDANCE_REQUEST',
  MARK_ATTENDANCE_SUCCESS: 'MARK_ATTENDANCE_SUCCESS',
  MARK_ATTENDANCE_FAIL: 'MARK_ATTENDANCE_FAIL',

  UPDATE_SESSION_REQUEST: 'UPDATE_SESSION_REQUEST',
  UPDATE_SESSION_SUCCESS: 'UPDATE_SESSION_SUCCESS',
  UPDATE_SESSION_FAIL: 'UPDATE_SESSION_FAIL',

  CANCEL_SESSION_REQUEST: 'CANCEL_SESSION_REQUEST',
  CANCEL_SESSION_SUCCESS: 'CANCEL_SESSION_SUCCESS',
  CANCEL_SESSION_FAIL: 'CANCEL_SESSION_FAIL',

  JOIN_SESSION_REQUEST: 'JOIN_SESSION_REQUEST',
  JOIN_SESSION_SUCCESS: 'JOIN_SESSION_SUCCESS',
  JOIN_SESSION_FAIL: 'JOIN_SESSION_FAIL',

  // Group Chat
  GET_CHAT_MESSAGES_REQUEST: 'GET_CHAT_MESSAGES_REQUEST',
  GET_CHAT_MESSAGES_SUCCESS: 'GET_CHAT_MESSAGES_SUCCESS',
  GET_CHAT_MESSAGES_FAIL: 'GET_CHAT_MESSAGES_FAIL',

  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAIL: 'SEND_MESSAGE_FAIL',

  EDIT_MESSAGE_REQUEST: 'EDIT_MESSAGE_REQUEST',
  EDIT_MESSAGE_SUCCESS: 'EDIT_MESSAGE_SUCCESS',
  EDIT_MESSAGE_FAIL: 'EDIT_MESSAGE_FAIL',

  DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
  DELETE_MESSAGE_SUCCESS: 'DELETE_MESSAGE_SUCCESS',
  DELETE_MESSAGE_FAIL: 'DELETE_MESSAGE_FAIL',

  ADD_REACTION_REQUEST: 'ADD_REACTION_REQUEST',
  ADD_REACTION_SUCCESS: 'ADD_REACTION_SUCCESS',
  ADD_REACTION_FAIL: 'ADD_REACTION_FAIL',

  MARK_MESSAGES_READ_REQUEST: 'MARK_MESSAGES_READ_REQUEST',
  MARK_MESSAGES_READ_SUCCESS: 'MARK_MESSAGES_READ_SUCCESS',
  MARK_MESSAGES_READ_FAIL: 'MARK_MESSAGES_READ_FAIL',

  GET_UNREAD_COUNT_REQUEST: 'GET_UNREAD_COUNT_REQUEST',
  GET_UNREAD_COUNT_SUCCESS: 'GET_UNREAD_COUNT_SUCCESS',
  GET_UNREAD_COUNT_FAIL: 'GET_UNREAD_COUNT_FAIL',

  SEARCH_MESSAGES_REQUEST: 'SEARCH_MESSAGES_REQUEST',
  SEARCH_MESSAGES_SUCCESS: 'SEARCH_MESSAGES_SUCCESS',
  SEARCH_MESSAGES_FAIL: 'SEARCH_MESSAGES_FAIL',

  // UI State
  CLEAR_ERRORS: 'CLEAR_STUDY_GROUP_ERRORS',
  CLEAR_SUCCESS: 'CLEAR_STUDY_GROUP_SUCCESS',
  SET_LOADING: 'SET_STUDY_GROUP_LOADING',
  RESET_STATE: 'RESET_STUDY_GROUP_STATE',

  ONNECT_TO_GROUP_CHAT: 'CONNECT_TO_GROUP_CHAT',
  DISCONNECT_FROM_GROUP_CHAT: 'DISCONNECT_FROM_GROUP_CHAT',
  SET_GROUP_CHAT_CONNECTED: 'SET_GROUP_CHAT_CONNECTED',
  
  // Messages
  ADD_GROUP_MESSAGE: 'ADD_GROUP_MESSAGE',
  UPDATE_GROUP_MESSAGE: 'UPDATE_GROUP_MESSAGE',
  REMOVE_GROUP_MESSAGE: 'REMOVE_GROUP_MESSAGE',
  SET_MESSAGE_SENDING: 'SET_MESSAGE_SENDING',
  
  // Typing
  SET_GROUP_TYPING: 'SET_GROUP_TYPING',
  CLEAR_GROUP_TYPING: 'CLEAR_GROUP_TYPING',
  
  // Online Status
  SET_GROUP_ONLINE_MEMBERS: 'SET_GROUP_ONLINE_MEMBERS',
  ADD_GROUP_ONLINE_MEMBER: 'ADD_GROUP_ONLINE_MEMBER',
  REMOVE_GROUP_ONLINE_MEMBER: 'REMOVE_GROUP_ONLINE_MEMBER',
  
  // Reactions
  UPDATE_GROUP_MESSAGE_REACTIONS: 'UPDATE_GROUP_MESSAGE_REACTIONS',
  
  // Read Status
  UPDATE_GROUP_MESSAGE_READ_STATUS: 'UPDATE_GROUP_MESSAGE_READ_STATUS',
  
  // Mentions
  ADD_GROUP_MENTION: 'ADD_GROUP_MENTION',
  MARK_GROUP_MENTION_READ: 'MARK_GROUP_MENTION_READ',
  CLEAR_GROUP_MENTIONS: 'CLEAR_GROUP_MENTIONS',
  
  // Errors
  SET_GROUP_CHAT_ERROR: 'SET_GROUP_CHAT_ERROR',
  CLEAR_GROUP_CHAT_ERROR: 'CLEAR_GROUP_CHAT_ERROR',

    ADD_GROUP_MESSAGE: 'ADD_GROUP_MESSAGE',
  UPDATE_GROUP_MESSAGE: 'UPDATE_GROUP_MESSAGE',
  REMOVE_GROUP_MESSAGE: 'REMOVE_GROUP_MESSAGE',
  SET_GROUP_TYPING: 'SET_GROUP_TYPING',
  CLEAR_GROUP_TYPING: 'CLEAR_GROUP_TYPING',
  SET_GROUP_ONLINE_MEMBERS: 'SET_GROUP_ONLINE_MEMBERS',
  ADD_GROUP_ONLINE_MEMBER: 'ADD_GROUP_ONLINE_MEMBER',
  REMOVE_GROUP_ONLINE_MEMBER: 'REMOVE_GROUP_ONLINE_MEMBER',
  UPDATE_GROUP_MESSAGE_REACTIONS: 'UPDATE_GROUP_MESSAGE_REACTIONS',
  UPDATE_GROUP_MESSAGE_READ_STATUS: 'UPDATE_GROUP_MESSAGE_READ_STATUS',
  ADD_GROUP_MENTION: 'ADD_GROUP_MENTION',
  SET_GROUP_CHAT_CONNECTED: 'SET_GROUP_CHAT_CONNECTED',
  SET_GROUP_CHAT_ERROR: 'SET_GROUP_CHAT_ERROR',
  CLEAR_GROUP_CHAT_ERROR: 'CLEAR_GROUP_CHAT_ERROR',
  
  // Private chat types (for compatibility)
  LOAD_CONVERSATIONS: 'LOAD_CONVERSATIONS',
  LOAD_MESSAGES: 'LOAD_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  MESSAGE_SENT: 'MESSAGE_SENT',
  SET_TYPING: 'SET_TYPING',
  CLEAR_TYPING: 'CLEAR_TYPING',
  UPDATE_ONLINE_USERS: 'UPDATE_ONLINE_USERS',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  CHAT_ERROR: 'CHAT_ERROR'
};