export const announcementsData = [
  {
    id: 1,
    title: "Welcome to Spring 2024 Semester",
    message: "We're excited to welcome all students to the new semester. Please check your course schedules and attend the orientation session on January 20th.",
    author: "John Smith",
    date: "2024-01-15",
    priority: "high",
    category: "General",
  },
  {
    id: 2,
    title: "New Course: Advanced React Development",
    message: "We're pleased to announce a new advanced React course starting February 1st. Limited seats available - register early!",
    author: "Dr. Sarah Johnson",
    date: "2024-01-14",
    priority: "medium",
    category: "Courses",
  },
  {
    id: 3,
    title: "Library Hours Extended",
    message: "The university library will now be open until 11 PM on weekdays to support your studies during exam period.",
    author: "Lisa Thompson",
    date: "2024-01-13",
    priority: "low",
    category: "Facilities",
  },
  {
    id: 4,
    title: "Student Registration Deadline",
    message: "Reminder: The deadline for course registration is January 25th. Please ensure all your courses are registered by this date.",
    author: "Admin Office",
    date: "2024-01-12",
    priority: "high",
    category: "Registration",
  },
  {
    id: 5,
    title: "Career Fair 2024",
    message: "Join us for the annual career fair on March 15th. Over 50 companies will be present with internship and job opportunities.",
    author: "Career Services",
    date: "2024-01-11",
    priority: "medium",
    category: "Events",
  },
];