export const coursesData = [
  {
    id: 1,
    title: "React Fundamentals",
    code: "CS-301",
    category: "Computer Science",
    instructors: ["Dr. Sarah Johnson", "Prof. Michael Davis"],
    enrolledStudents: 245,
    status: "Active",
    startDate: "2024-01-15",
    duration: "12 weeks",
  },
  {
    id: 2,
    title: "Python Programming",
    code: "CS-201",
    category: "Computer Science",
    instructors: ["Prof. Robert Wilson"],
    enrolledStudents: 198,
    status: "Active",
    startDate: "2024-01-08",
    duration: "10 weeks",
  },
  {
    id: 3,
    title: "Data Science Fundamentals",
    code: "DS-101",
    category: "Data Science",
    instructors: ["Dr. Amanda Lee", "Dr. Sarah Johnson"],
    enrolledStudents: 167,
    status: "Active",
    startDate: "2024-02-01",
    duration: "14 weeks",
  },
  {
    id: 4,
    title: "Web Design Principles",
    code: "DES-201",
    category: "Design",
    instructors: ["Prof. Lisa Martinez"],
    enrolledStudents: 143,
    status: "Active",
    startDate: "2024-01-22",
    duration: "8 weeks",
  },
  {
    id: 5,
    title: "Machine Learning Basics",
    code: "ML-301",
    category: "Machine Learning",
    instructors: ["Dr. James Anderson"],
    enrolledStudents: 121,
    status: "Inactive",
    startDate: "2024-03-01",
    duration: "16 weeks",
  },
  {
    id: 6,
    title: "Database Management",
    code: "DB-201",
    category: "Computer Science",
    instructors: ["Prof. Robert Wilson"],
    enrolledStudents: 89,
    status: "Active",
    startDate: "2024-01-29",
    duration: "12 weeks",
  },
];