export const forumCategoriesData = [
  {
    id: 1,
    category: "General Discussion",
    description: "General topics and conversations about university life",
    postsCount: 1247,
    lastActivity: "2024-01-15",
    moderators: ["John Smith", "Dr. Sarah Johnson"],
  },
  {
    id: 2,
    category: "Course Help",
    description: "Get help with your coursework and assignments",
    postsCount: 856,
    lastActivity: "2024-01-15",
    moderators: ["Prof. Robert Wilson", "Dr. Amanda Lee"],
  },
  {
    id: 3,
    category: "Technical Support",
    description: "Technical issues and platform support",
    postsCount: 234,
    lastActivity: "2024-01-14",
    moderators: ["Tech Support Team"],
  },
  {
    id: 4,
    category: "Study Groups",
    description: "Form and join study groups with fellow students",
    postsCount: 445,
    lastActivity: "2024-01-15",
    moderators: ["Student Council"],
  },
  {
    id: 5,
    category: "Career Guidance",
    description: "Career advice, internships, and job opportunities",
    postsCount: 178,
    lastActivity: "2024-01-13",
    moderators: ["Career Services"],
  },
  {
    id: 6,
    category: "Events & Activities",
    description: "University events, workshops, and social activities",
    postsCount: 312,
    lastActivity: "2024-01-14",
    moderators: ["Event Coordinators"],
  },
];